# workflows:
#   react-native-android:
#     name: React Native Android
#     max_build_duration: 120
#     instance_type: window_10
#     environment:
#       android_signing:
#         - keystore_reference
#       groups:
#         - google_play
#         - google_credentials
#       vars:
#         PACKAGE_NAME: "com.corehacker"
#     scripts:
#       - name: Set Android SDK location
#         script: | 
#           echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
#       - name: Install npm dependencies
#         script: | 
#           npm install
#       - name: Install Expo CLI and eject
#         script: | 
#           npm install -g expo-cli
#           expo eject
#       - name: Set up app/build.gradle
#         script: | 
#           mv ./support-files/build.gradle android/app
#       - name: Build Android release
#         script: | 
#           LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
#           if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
#               # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
#               UPDATED_BUILD_NUMBER=$BUILD_NUMBER
#           else
#               UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
#           fi
#           cd android
#           ./gradlew bundleRelease \
#             -PversionCode=$UPDATED_BUILD_NUMBER \
#             -PversionName=1.0.$UPDATED_BUILD_NUMBER
#     artifacts:
#       - android/app/build/outputs/**/*.aab
#     publishing:
#       email:
#         recipients:
#           - nandverma830@example.com
#           - nandv455@example.com
#         notify:
#           success: true
#           failure: false
#       google_play:
#         credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#         track: internal
#       in_app_update_priority: 3
#       rollout_fraction: 0.25
#       changes_not_sent_for_review: true
#       submit_as_draft: true
#       release_promotion:
#       track: alpha
#       rollout_fraction: 0.25
#       promote_as_draft: true



  workflows:
      sample-workflow:
          name: LearnCicd
          max_build_duration: 120
          instance_type: window_10
  workflows:
      android-workflow-id:
          name: Android Sample Workflow
          # .......    
          # .......
          # .......  
      ios-workflow-id:
          name: iOS Sample Workflow
          # ......

  workflows:
        android-workflow:
        name: Android Workflow
      # ....
  environment:
        android_signing:
          - keystore_reference
  workflows:
    react-native-android:
      # ....
      environment:
        groups:
          # ...
        vars:
          PACKAGE_NAME: "io.codemagic.sample.reactnative"
          scripts:
    # ....
  - name: Install npm dependencies
    script: | 
      npm install
  - name: Set Android SDK location
    script: | 
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
  - name: Build Android release
    script: | 
      cd android
      ./gradlew bundleRelease

artifacts:
  - android/app/build/outputs/**/*.aab